###
GET http://localhost:8080/dataio/suffix/findall
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/dataio/suffix/findone/1
Accept: application/json
Content-Type: application/json

###
POST http://localhost:8080/dataio/suffix/addone
Accept: application/json
Content-Type: application/json

{
  "alphabetic": "ADD_TEST",
  "phonetic": "---"
}

###
DELETE http://localhost:8080/dataio/suffix/deleteone/1
Accept: application/json
Content-Type: application/json


###
#----------word test-----------------
GET http://localhost:8080/dataio/suffix/101/words

###
PUT http://localhost:8080/dataio/suffix/1/addword
Accept: application/json
Content-Type: application/json

{
  "alphabetic": "UPDATE_TEST",
  "phonetic": "---"
}

###
DELETE http://localhost:8080/dataio/suffix/1/delword
Accept: application/json
Content-Type: application/json

{
  "alphabetic": "UPDATE_TEST",
  "phonetic": "---"
}

