###
GET http://localhost:8080/dataio/word/findall
Accept: application/json
Content-Type: application/json
###
GET http://localhost:8080/dataio/word/findone/1
Accept: application/json
Content-Type: application/json
###
POST http://localhost:8080/dataio/word/addone
Accept: application/json
Content-Type: application/json

{
  "alphabetic": "ADD_TEST",
  "phonetic": "---"
}

###
#------------------------------------
POST http://localhost:8080/dataio/word/addone
Accept: application/json
Content-Type: application/json

{
  "alphabetic": "12345",
  "phonetic": "---"
}

###

DELETE http://localhost:8080/dataio/word/deleteone/1
Accept: application/json
Content-Type: application/json

###
PUT http://localhost:8080/dataio/word/updateone/1
Accept: application/json
Content-Type: application/json

{
  "alphabetic": "UPDATE_TEST",
  "phonetic": "---"
}

###
